---
port_profiles:
  - profile: Hypervisor_Hosts
    mode: trunk
    vlans: "110-111,120-121,130-131"
    spanning_tree_portfast: edge
  - profile: VLAN_10
    mode: access
    vlans: 10
    port_channel:
      mode: active
  - profile: VLAN_20
    mode: access
    vlans: 20
    port_channel:
      mode: active
  - profile: DB_Clusters
    mode: trunk
    vlans: "140-141"