---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true
# underlay_rfc5549: true
underlay_multicast: true
evpn_multicast: true

underlay_multicast_rps:
  - rp: 192.168.109.10
    nodes:
      - name: spine1
        loopback_number: 10
    groups:
      - 239.0.0.0/22



  #isis_area_id: 49.0001
  #ishis_system_id_format: underlay_loopback

  #underlay_routing_protocol: isis

# Spine Switches
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 101
      mgmt_ip: 172.20.20.101/24

# leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65100-65199 # Gives a range which will be auto-assigned
    platform: cEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.102.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet1] # leaf uplinks
    uplink_switches: [spine1] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.110.0/22 # For the p2p interfaces to chopped up into /31s
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: false
  nodes:
    - name: leaf1
      id: 1
      mgmt_ip: 172.20.20.11/24
      uplink_switch_interfaces: [Ethernet1]
    - name: leaf2
      id: 2
      mgmt_ip: 172.20.20.12/24
      uplink_switch_interfaces: [Ethernet2]

# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1550

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
dns_domain: tony.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 172.20.20.1
name_servers: [192.168.1.9]


local_users:
  - name: tony
    privilege: 15
    role: network-admin
    no_password: True
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwcRUzAE9qoos9ftWtER5H/cjK3VeE9vA3ugS+aPdYGZVFsOkeC9YuGQ1PXslp+VAoD1bFMuQNsmAKdtfLgDx+XdV/5KoBudvgQDn9KAtX7/lU8TgrFvHLsijbMNyDnMN0lovbHSEADh0s15dLsnWsFJ1AMIHY2CSyh4SwoJQraAr+6VYLM6lLC7WptfLn9Wm3VReP0fFAoPXhPROIB/EGyNPHEUaom/nK4r1mw8nRvb2hc3/8pFR0Uj87rW2g5nDSaqwJHtMEq2ffCQY+QsCVn5MDC/WQgf4ZTsqtXvWoZQwpCUjVP6b1EQnbjraXXZRPuwAeblfej5BZqIhmk1ME7TLBlnaILEpjRYUdEkqg+wLD2hky7TK8e/uQavbuAcSlnN5BuNPfZi9rBlu9yQwLaHGd1c6CSEM1Y9BtHH82KSpYeb76Jl3WtDg16ae/u9en32AqhN9t1IuJAGcQdA4TZxDXzpUohoSIT4M72FsH2yfvOaDHErYxgJhpdzfX1IE= tony@autobox-live-1"
  - name: admin
    privilege: 15
    role: network-admin
    no_password: True
    sha512_password: "$6$NZ12Yq8utIdvS7ku$4WCFK1LfF946G/Zxca0z0M4OHvQp0EKyNXoHtesvjLQx75V.LMb8BFTGSd0OScTSy.ieohjAokoImHArPJ9QN1"
management_api:
  enable_https: true

aaa_authentication:
  login:
    default: local

aaa_authorization:
  exec: 
    default: local

          #     - aaa authentication login default local 
          # - aaa authorization exec default local



# cvp_instance_ips: [192.168.1.201]
# cvp_token_file: /tmp/token
