---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true
# underlay_rfc5549: true
underlay_multicast: true
evpn_multicast: true

underlay_multicast_rps:
  - rp: 192.168.109.10
    nodes:
      - name: spine1
        loopback_number: 10
      - name: spine2
        loopback_number: 10
    groups:
      - 239.0.0.0/22



  #isis_area_id: 49.0001
  #ishis_system_id_format: underlay_loopback

  #underlay_routing_protocol: isis

# Spine Switches
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 101
      mgmt_ip: 172.20.20.101/24
    - name: spine2
      id: 102
      mgmt_ip: 172.20.20.102/24

# leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65100-65199 # Gives a range which will be auto-assigned
    platform: cEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.102.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4] # leaf uplinks
    uplink_switches: [spine1, spine2] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.110.0/22 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG
  nodes:
    - name: leaf1
      id: 1
      mgmt_ip: 172.20.20.11/24
      uplink_switch_interfaces: [Ethernet3, Ethernet3]
    - name: leaf2
      id: 2
      mgmt_ip: 172.20.20.12/24
      uplink_switch_interfaces: [Ethernet4, Ethernet4]
    - name: leaf3
      id: 3
      mgmt_ip: 172.20.20.13/24
      uplink_switch_interfaces: [Ethernet5, Ethernet5]
    - name: leaf4
      id: 4
      mgmt_ip: 172.20.20.14/24
      uplink_switch_interfaces: [Ethernet6, Ethernet6]
    

# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1550

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
dns_domain: tony.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 172.20.20.1
name_servers: [192.168.1.9]


local_users:
  - name: tony
    privilege: 15
    role: network-admin
    no_password: True
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCUrro9HRd2CeRRS69Yn7Lz8fHfNEj3877gbXSb7eBdzMOFDMd05AWj/4reNc1hRyy8DGx/JXrfLzaJBbh9731cy+4kl2/gtIvin0T3ZWtHJ3HaBTZIRDtoI5Pgnpz1C4Zk/cQZM82RgF7SoQBCAx+dxj73FPylw8zBAtsgFl+t64L8N3atjQn7ThCc7QpPPrefh29WRchKH67Zormq6jX5bNZ/kUUw7fF2Sx4AzL9Ox5MmAiu05rvTm7+hLkahJfBghmKHzeNtZVoUkY7T0sAIQIJ+d/7xjwBrG0Lw2d89jaBmeUU3bbuIxG6nReQ7hWMlTzvxadMfyyf8y792ZRxTr93OPSGBdbS1GuZ15NM9HvP8nx+5V/Xt2fQBS+yc+NypIUwR2swUtyBrnAWYXL7KihO5BlP1JGGuGYYUUGlZlJDNNYeOT4EUhhPJ8peCHsbNqagEbxrrC9I87jKADcSJNyjYxorFN8Crh9rB8HPWFNtolTr/IrVwQliuPHSeNC0= tony@evpn-book"
  - name: admin
    privilege: 15
    role: network-admin
    no_password: True
    sha512_password: "$6$NZ12Yq8utIdvS7ku$4WCFK1LfF946G/Zxca0z0M4OHvQp0EKyNXoHtesvjLQx75V.LMb8BFTGSd0OScTSy.ieohjAokoImHArPJ9QN1"
management_api:
  enable_https: true

aaa_authentication:
  login:
    default: local

aaa_authorization:
  exec: 
    default: local

          #     - aaa authentication login default local 
          # - aaa authorization exec default local



# cvp_instance_ips: [192.168.1.201]
# cvp_token_file: /tmp/token
